/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.metaparticle.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The Container model.
 */
public class Container {
    /**
     * The image property.
     */
    @JsonProperty(value = "image", required = true)
    private String image;

    /**
     * The env property.
     */
    @JsonProperty(value = "env")
    private List<EnvVar> env;

    /**
     * Get the image value.
     *
     * @return the image value
     */
    public String image() {
        return this.image;
    }

    /**
     * Set the image value.
     *
     * @param image the image value to set
     * @return the Container object itself.
     */
    public Container withImage(String image) {
        this.image = image;
        return this;
    }

    /**
     * Get the env value.
     *
     * @return the env value
     */
    public List<EnvVar> env() {
        return this.env;
    }

    /**
     * Set the env value.
     *
     * @param env the env value to set
     * @return the Container object itself.
     */
    public Container withEnv(List<EnvVar> env) {
        this.env = env;
        return this;
    }

}
