/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.metaparticle.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The JobSpecification model.
 */
public class JobSpecification {
    /**
     * The name property.
     */
    @JsonProperty(value = "name", required = true)
    private String name;

    /**
     * The containers property.
     */
    @JsonProperty(value = "containers")
    private List<Container> containers;

    /**
     * The replicas property.
     */
    @JsonProperty(value = "replicas")
    private Integer replicas;

    /**
     * The schedule property.
     */
    @JsonProperty(value = "schedule")
    private String schedule;

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the JobSpecification object itself.
     */
    public JobSpecification withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the containers value.
     *
     * @return the containers value
     */
    public List<Container> containers() {
        return this.containers;
    }

    /**
     * Set the containers value.
     *
     * @param containers the containers value to set
     * @return the JobSpecification object itself.
     */
    public JobSpecification withContainers(List<Container> containers) {
        this.containers = containers;
        return this;
    }

    /**
     * Get the replicas value.
     *
     * @return the replicas value
     */
    public Integer replicas() {
        return this.replicas;
    }

    /**
     * Set the replicas value.
     *
     * @param replicas the replicas value to set
     * @return the JobSpecification object itself.
     */
    public JobSpecification withReplicas(Integer replicas) {
        this.replicas = replicas;
        return this;
    }

    /**
     * Get the schedule value.
     *
     * @return the schedule value
     */
    public String schedule() {
        return this.schedule;
    }

    /**
     * Set the schedule value.
     *
     * @param schedule the schedule value to set
     * @return the JobSpecification object itself.
     */
    public JobSpecification withSchedule(String schedule) {
        this.schedule = schedule;
        return this;
    }

}
