/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.metaparticle.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The ServicePort model.
 */
public class ServicePort {
    /**
     * The number property.
     */
    @JsonProperty(value = "number", required = true)
    private int number;

    /**
     * The protocol property.
     */
    @JsonProperty(value = "protocol")
    private String protocol;

    /**
     * Get the number value.
     *
     * @return the number value
     */
    public int number() {
        return this.number;
    }

    /**
     * Set the number value.
     *
     * @param number the number value to set
     * @return the ServicePort object itself.
     */
    public ServicePort withNumber(int number) {
        this.number = number;
        return this;
    }

    /**
     * Get the protocol value.
     *
     * @return the protocol value
     */
    public String protocol() {
        return this.protocol;
    }

    /**
     * Set the protocol value.
     *
     * @param protocol the protocol value to set
     * @return the ServicePort object itself.
     */
    public ServicePort withProtocol(String protocol) {
        this.protocol = protocol;
        return this;
    }

}
