/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.metaparticle.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The Service model.
 */
public class Service {
    /**
     * The guid property.
     */
    @JsonProperty(value = "guid", required = true)
    private long guid;

    /**
     * The name property.
     */
    @JsonProperty(value = "name", required = true)
    private String name;

    /**
     * The services property.
     */
    @JsonProperty(value = "services")
    private List<ServiceSpecification> services;

    /**
     * The jobs property.
     */
    @JsonProperty(value = "jobs")
    private List<JobSpecification> jobs;

    /**
     * The serve property.
     */
    @JsonProperty(value = "serve")
    private ServeSpecification serve;

    /**
     * Get the guid value.
     *
     * @return the guid value
     */
    public long guid() {
        return this.guid;
    }

    /**
     * Set the guid value.
     *
     * @param guid the guid value to set
     * @return the Service object itself.
     */
    public Service withGuid(long guid) {
        this.guid = guid;
        return this;
    }

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the Service object itself.
     */
    public Service withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the services value.
     *
     * @return the services value
     */
    public List<ServiceSpecification> services() {
        return this.services;
    }

    /**
     * Set the services value.
     *
     * @param services the services value to set
     * @return the Service object itself.
     */
    public Service withServices(List<ServiceSpecification> services) {
        this.services = services;
        return this;
    }

    /**
     * Get the jobs value.
     *
     * @return the jobs value
     */
    public List<JobSpecification> jobs() {
        return this.jobs;
    }

    /**
     * Set the jobs value.
     *
     * @param jobs the jobs value to set
     * @return the Service object itself.
     */
    public Service withJobs(List<JobSpecification> jobs) {
        this.jobs = jobs;
        return this;
    }

    /**
     * Get the serve value.
     *
     * @return the serve value
     */
    public ServeSpecification serve() {
        return this.serve;
    }

    /**
     * Set the serve value.
     *
     * @param serve the serve value to set
     * @return the Service object itself.
     */
    public Service withServe(ServeSpecification serve) {
        this.serve = serve;
        return this;
    }

}
