/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.metaparticle.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The ServiceSpecification model.
 */
public class ServiceSpecification {
    /**
     * The name property.
     */
    @JsonProperty(value = "name", required = true)
    private String name;

    /**
     * The replicas property.
     */
    @JsonProperty(value = "replicas")
    private Integer replicas;

    /**
     * The shardSpec property.
     */
    @JsonProperty(value = "shardSpec")
    private ShardSpecification shardSpec;

    /**
     * The containers property.
     */
    @JsonProperty(value = "containers")
    private List<Container> containers;

    /**
     * The ports property.
     */
    @JsonProperty(value = "ports")
    private List<ServicePort> ports;

    /**
     * The reference property.
     */
    @JsonProperty(value = "reference")
    private String reference;

    /**
     * The depends property.
     */
    @JsonProperty(value = "depends")
    private String depends;

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the ServiceSpecification object itself.
     */
    public ServiceSpecification withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the replicas value.
     *
     * @return the replicas value
     */
    public Integer replicas() {
        return this.replicas;
    }

    /**
     * Set the replicas value.
     *
     * @param replicas the replicas value to set
     * @return the ServiceSpecification object itself.
     */
    public ServiceSpecification withReplicas(Integer replicas) {
        this.replicas = replicas;
        return this;
    }

    /**
     * Get the shardSpec value.
     *
     * @return the shardSpec value
     */
    public ShardSpecification shardSpec() {
        return this.shardSpec;
    }

    /**
     * Set the shardSpec value.
     *
     * @param shardSpec the shardSpec value to set
     * @return the ServiceSpecification object itself.
     */
    public ServiceSpecification withShardSpec(ShardSpecification shardSpec) {
        this.shardSpec = shardSpec;
        return this;
    }

    /**
     * Get the containers value.
     *
     * @return the containers value
     */
    public List<Container> containers() {
        return this.containers;
    }

    /**
     * Set the containers value.
     *
     * @param containers the containers value to set
     * @return the ServiceSpecification object itself.
     */
    public ServiceSpecification withContainers(List<Container> containers) {
        this.containers = containers;
        return this;
    }

    /**
     * Get the ports value.
     *
     * @return the ports value
     */
    public List<ServicePort> ports() {
        return this.ports;
    }

    /**
     * Set the ports value.
     *
     * @param ports the ports value to set
     * @return the ServiceSpecification object itself.
     */
    public ServiceSpecification withPorts(List<ServicePort> ports) {
        this.ports = ports;
        return this;
    }

    /**
     * Get the reference value.
     *
     * @return the reference value
     */
    public String reference() {
        return this.reference;
    }

    /**
     * Set the reference value.
     *
     * @param reference the reference value to set
     * @return the ServiceSpecification object itself.
     */
    public ServiceSpecification withReference(String reference) {
        this.reference = reference;
        return this;
    }

    /**
     * Get the depends value.
     *
     * @return the depends value
     */
    public String depends() {
        return this.depends;
    }

    /**
     * Set the depends value.
     *
     * @param depends the depends value to set
     * @return the ServiceSpecification object itself.
     */
    public ServiceSpecification withDepends(String depends) {
        this.depends = depends;
        return this;
    }

}
