/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.metaparticle.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The ServeSpecification model.
 */
public class ServeSpecification {
    /**
     * The name property.
     */
    @JsonProperty(value = "name", required = true)
    private String name;

    /**
     * The publicProperty property.
     */
    @JsonProperty(value = "public")
    private Boolean publicProperty;

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the ServeSpecification object itself.
     */
    public ServeSpecification withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the publicProperty value.
     *
     * @return the publicProperty value
     */
    public Boolean publicProperty() {
        return this.publicProperty;
    }

    /**
     * Set the publicProperty value.
     *
     * @param publicProperty the publicProperty value to set
     * @return the ServeSpecification object itself.
     */
    public ServeSpecification withPublicProperty(Boolean publicProperty) {
        this.publicProperty = publicProperty;
        return this;
    }

}
