/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.metaparticle.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The ShardSpecification model.
 */
public class ShardSpecification {
    /**
     * The fieldPath property.
     */
    @JsonProperty(value = "fieldPath")
    private String fieldPath;

    /**
     * The urlPattern property.
     */
    @JsonProperty(value = "urlPattern")
    private String urlPattern;

    /**
     * The shards property.
     */
    @JsonProperty(value = "shards")
    private Integer shards;

    /**
     * Get the fieldPath value.
     *
     * @return the fieldPath value
     */
    public String fieldPath() {
        return this.fieldPath;
    }

    /**
     * Set the fieldPath value.
     *
     * @param fieldPath the fieldPath value to set
     * @return the ShardSpecification object itself.
     */
    public ShardSpecification withFieldPath(String fieldPath) {
        this.fieldPath = fieldPath;
        return this;
    }

    /**
     * Get the urlPattern value.
     *
     * @return the urlPattern value
     */
    public String urlPattern() {
        return this.urlPattern;
    }

    /**
     * Set the urlPattern value.
     *
     * @param urlPattern the urlPattern value to set
     * @return the ShardSpecification object itself.
     */
    public ShardSpecification withUrlPattern(String urlPattern) {
        this.urlPattern = urlPattern;
        return this;
    }

    /**
     * Get the shards value.
     *
     * @return the shards value
     */
    public Integer shards() {
        return this.shards;
    }

    /**
     * Set the shards value.
     *
     * @param shards the shards value to set
     * @return the ShardSpecification object itself.
     */
    public ShardSpecification withShards(Integer shards) {
        this.shards = shards;
        return this;
    }

}
